language: php
php:
  - 7.2
  - 7.3
  - 7.4
  - nightly
jobs:
  allow_failures:
    - php: nightly
matrix:
  allow_failures:
    - php: nightly
  include:
    - php: 7.4
      env: PREFER_LOWEST="--prefer-lowest"
    - php: 7.2
      env: PREFER_LOWEST="--prefer-lowest"

before_script:
  - composer self-update
  - travis_retry composer install --prefer-dist --no-interaction --ignore-platform-reqs
  - travis_retry composer  update --prefer-dist --no-interaction $PREFER_LOWEST --ignore-platform-reqs
script:
  - composer test
