on:
  - pull_request
  - push

name: CI

jobs:
  tests:
    name: Tests

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest

        php:
          - "8.1"

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install PHP with extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, opcache

      - name: Install composer dependencies
        run: composer update --no-ansi --no-interaction --no-progress

      - name: Run tests
        run: composer test
